update general css 4rule
fullstack-development/front-end-best-practices pull request #13
Opened 2019-04-05 03:35 UTC by krashaen

#11 Дополнил правило

2019-04-05 04:04 UTC, Znack approved these changes

2019-04-05 04:05 UTC, Znack commented
@chmnkh норм, мержим?

2019-04-05 08:04 UTC, chmnkh requested changes

2019-04-05 08:04 UTC, chmnkh commented on CSS/generalRequirements.md
> +    >Папки блоков нельзя вкладывать друг в друга.
Во-первых, мне не совсем понятно, почему эти два правила сюда добавлены. Я бы их добавил в файл по бэму скорее. Во-вторых, я бы не стал второе правило на уровне стандарта вообще вводить, потому что это как минимум холиварная тема. Мы, например, на прошлом проекте вкладывали блоки в другие блоки (причем этому решению опять же предшествовал холивар).

2019-04-05 08:09 UTC, Znack commented on CSS/generalRequirements.md
> +    >Папки блоков нельзя вкладывать друг в друга.
И какие преимущества вкладывать? Вкладывание — это по сути зацепление контекста, теперь ты точно никогда не можешь переиспользовать блок в другом месте. А если нет смысла рассматривать блок без контекста, то зачем это выделять в отдельный блок? :)

2019-04-05 08:35 UTC, chmnkh commented on CSS/generalRequirements.md
> +    >Папки блоков нельзя вкладывать друг в друга.
1) У нас на мобилу были отдельные мобильные версии блоков. Т.е. по смыслу - это одна и та же фигня только на мобилу, но формально это уже другой блок с другим именем. Нам было удобно класть такие "мобильные" блоки рядом с "обычными-десктопными" их версиями. 
2) В принципе какими бы в теории блоки не были "независимыми", постоянно возникают случаи, когда нужно какой-то их кусок вынести в свою компоненту тупо для удобства разработки. Притом что вероятность переиспользования этого куска вообще нулевая почти. В таких случаях его бывает удобно вложить в тот блок, в котором он будет использоваться, чтобы он среди других блоков не мазолил глаза. Когда куча блоков появляется в одной папке, это в принципе помогает лучше ориентироваться. Но с другой стороны это штука тонкая и в общем случае нету строгого правила, когда стоит класть на один уровень со всеми блоками, а когда вкладывать. Короче такое, мы спорили спорили на эту тему (как раз я топил за то чтобы плоско делать), и в итоге сошлись на том что будем вкладывать. Непростой вопрос, короч.

2019-04-05 10:31 UTC, Znack commented on CSS/generalRequirements.md
> +    >Папки блоков нельзя вкладывать друг в друга.
1. Там это не совсем блоки всё-таки. Это не самодостаточные архитектурные единицы, так как каждый из них зависил от контекста. В таких случаях надо придумывать подабстракции
1. Почти наверняка там была неудобная декомпозиция, ну или ничего страшного, что кажется вероятность переиспользования практичеки нулевой. Нередко это только кажется и только на начальном этапе написания такого кода. Тут очень много нюансов и надо на конкертных примерах рассматривать. 

Я думаю, норм пункт, и я думаю, что если разработчики опытные, они могут себе в редких случаях от стандартов отойти и подумать, как сделать хитрые выкрутасы в проекте грамотней. Зато это точно полезно новичкам, которые не будут костылять лишний раз, пусть лучше в отдельные блок вынесут такие вещи, как у тебя во втором пункте

2019-04-05 10:43 UTC, chmnkh commented on CSS/generalRequirements.md
> +    >Папки блоков нельзя вкладывать друг в друга.
ну да, согласен в целом

2019-04-05 10:46 UTC, chmnkh commented on CSS/generalRequirements.md
> +    >Папки блоков нельзя вкладывать друг в друга.
но тем не менее, я бы это правило все-таки перенес в бэм отдельным пунктом где-нибудь в начале, и сформулировал бы как-нибудь типа

> Все блоки должны лежать в своих папках и не должны быть вложены в папки других блоков.

2019-04-05 11:51 UTC, Znack commented on CSS/generalRequirements.md
> +    >Папки блоков нельзя вкладывать друг в друга.
Ну про БЭМ согласен, да

2019-04-09 07:09 UTC, chmnkh approved these changes

2019-04-09 07:15 UTC, merged