Fix bad example
fullstack-development/front-end-best-practices pull request #24
Opened 2019-08-09 04:27 UTC by Znack

2019-08-09 05:05 UTC, sk1e requested changes

2019-08-09 05:05 UTC, sk1e commented on CSS/bem.md
> +    > Например, в хэдере у нас находится обычная голубая кнопка, но она должна иметь большой отступ от соседа слева, для этого мы добавим `div.header__button`:
в коде соседа нет, а воображать это неудобно когда ты показываешь пример с кодом. Лучше добавить ещё лейбл и показать на примере обычного (не большого) отступа от этого лейбла

2019-08-09 05:06 UTC, Znack commented on CSS/bem.md
> +    > Например, в хэдере у нас находится обычная голубая кнопка, но она должна иметь большой отступ от соседа слева, для этого мы добавим `div.header__button`:
> показать на примере обычного (не большого) отступа от этого лейбла

а ты про какой небольшой отступ тут говоришь?

2019-08-09 05:09 UTC, sk1e commented on CSS/bem.md
> +    > Например, в хэдере у нас находится обычная голубая кнопка, но она должна иметь большой отступ от соседа слева, для этого мы добавим `div.header__button`:
я про эту часть у тебя:

>она должна иметь **большой** отступ от соседа слева

не надо подчёркивать величину эту отступа, в примере с лейблом она не будет иметь значения. Там важно что он просто есть.

2019-08-10 07:13 UTC, sk1e approved these changes

2019-08-10 07:16 UTC, merged