Change react handlers convention
fullstack-development/front-end-best-practices pull request #30
Opened 2019-11-14 07:40 UTC by chmnkh

Изменил описание для именования хэндлеров в реакте:
1. сделал проще некоторые формулировки;
2. переписал "в react-компоненте, атрибуты пропсов, относящиеся к обработке событий компонента, должны именоваться по шаблону `onElementNameEventName". Потому что такое ощущение, что мы должны в интерфейсе отражать кишки компоненты, а это какая-то дичь.

2019-11-14 07:47 UTC, krashaen approved these changes

2019-11-14 07:54 UTC, kinda-neat requested changes

2019-11-14 07:54 UTC, kinda-neat commented on JS/goodPractice.md
> +        * Пропсы react-компоненты, относящиеся к обработке событий, должны именоваться по шаблону `onEventName`, где `EventName` — имя обрабатываемого события. Каждое значение такой пропсы должно име
react мб с большой буквы?

2019-11-14 07:54 UTC, kinda-neat commented on JS/goodPractice.md
> +        * Пропсы react-компоненты, относящиеся к обработке событий, должны именоваться по шаблону `onEventName`, где `EventName` — имя обрабатываемого события. Каждое значение такой пропсы должно име
тут надо конечно понимать более широко понятие "событие", просто частенько воспринимается прям как click, blur, etc., а так событием так же считается onTabSelect какой-нибудь, события на уровне сущности, а не DOM (это просто коммент, не знаю насколько надо отражать здесь, ну и это другой вопрос)

2019-11-14 07:54 UTC, kinda-neat commented on JS/goodPractice.md
> +        * Пропсы react-компоненты, относящиеся к обработке событий, должны именоваться по шаблону `onEventName`, где `EventName` — имя обрабатываемого события. Каждое значение такой пропсы должно име
насчет handleComponentNameEventName этого не совсем согласен, зачем прям отражать название компоненты? чаще всего из контекста понятно что это за модалка (если она одна) и поэтому достаточно написать handleModalClose вместо handleCreateReportModalClose

2019-11-14 07:54 UTC, kinda-neat commented on JS/goodPractice.md
> +        * Обработчики событий на хост-узлах внутри компоненты (div, span и т.д.) должны именоваться по шаблону `onElementNameEventName`, где `ElementName` - имя БЭМ-элемента. Пример: `<div className=
шаблон onElementNameEventName, а в примере handleCancelButtonClick

2019-11-14 07:54 UTC, in19farkt requested changes

2019-11-14 07:54 UTC, in19farkt commented on JS/goodPractice.md
> +        * Обработчики событий на хост-узлах внутри компоненты (div, span и т.д.) должны именоваться по шаблону `onElementNameEventName`, где `ElementName` - имя БЭМ-элемента. Пример: `<div className=
тут очепятка
```diff
- должны именоваться по шаблону `onElementNameEventName`
+ должны именоваться по шаблону `handleElementNameEventName`
```

2019-11-14 07:54 UTC, in19farkt commented on JS/goodPractice.md
> +        * Обработчики событий на хост-узлах внутри компоненты (div, span и т.д.) должны именоваться по шаблону `onElementNameEventName`, где `ElementName` - имя БЭМ-элемента. Пример: `<div className=
Макс опередил :)

2019-11-14 07:55 UTC, Zarwlar approved these changes

2019-11-14 07:59 UTC, kinda-neat requested changes

2019-11-14 07:59 UTC, kinda-neat commented on JS/goodPractice.md
> +    > То есть не использовать "this.value". Вместо этого получать данные через объект события  "e.currentTarget.value".
я предлагаю всегда к таким md правкам всегда прикладывать ссылку вот так
https://github.com/fullstack-development/front-end-best-practices/blob/change-handlers-convention/JS/goodPractice.md в description
чтобы визуально можно было оценить не поехало ли чего

2019-11-14 08:00 UTC, sk1e requested changes

2019-11-14 08:00 UTC, sk1e commented on JS/goodPractice.md
> +        * Обработчики событий на хост-узлах внутри компоненты (div, span и т.д.) должны именоваться по шаблону `onElementNameEventName`, где `ElementName` - имя БЭМ-элемента. Пример: `<div className=
что за термин - «хост узел»?

2019-11-14 08:00 UTC, sk1e commented on JS/goodPractice.md
> +        * Пропсы react-компоненты, относящиеся к обработке событий, должны именоваться по шаблону `onEventName`, где `EventName` — имя обрабатываемого события. Каждое значение такой пропсы должно име
пример с модалкой - плохой. Для модалки обычно желательно обернуть БЭМ-элементом, который охарактеризует предназначение модалки - модалка с авторизацией, например.  Нужно сначала объяснить что сущности требующие прокидывания хэндлеров делятся на БЭМ-элементы и реакт-компоненты в отрыве от БЭМ-дерева, а потом уже объяснять схему именования.

2019-11-14 08:01 UTC, in19farkt commented on JS/goodPractice.md
> +        * Пропсы react-компоненты, относящиеся к обработке событий, должны именоваться по шаблону `onEventName`, где `EventName` — имя обрабатываемого события. Каждое значение такой пропсы должно име
> зачем прям отражать название компоненты?

> поэтому достаточно написать handleModalClose

Ты тут по-моему путаешься в показаниях)) Спрашиваешь зачем отражать имя компоненты и тут же пишешь "достаточно написать handleModalClose", используя при этом название компоненты в имени обработчика. Поэтому для меня не понятно что в итоге ты имел ввиду

2019-11-14 08:02 UTC, kinda-neat commented on JS/goodPractice.md
> +        * Обработчики событий на хост-узлах внутри компоненты (div, span и т.д.) должны именоваться по шаблону `onElementNameEventName`, где `ElementName` - имя БЭМ-элемента. Пример: `<div className=
подразумевается базовый элемент предоставляемый платформой, типа дивов, параграфов и т.д., не тобой определенные короч

2019-11-14 08:04 UTC, sk1e commented on JS/goodPractice.md
> +        * Обработчики событий на хост-узлах внутри компоненты (div, span и т.д.) должны именоваться по шаблону `onElementNameEventName`, где `ElementName` - имя БЭМ-элемента. Пример: `<div className=
и откуда он взялся? Где его употребляют? Я впервые встретил

2019-11-14 08:05 UTC, chmnkh commented on JS/goodPractice.md
> +        * Пропсы react-компоненты, относящиеся к обработке событий, должны именоваться по шаблону `onEventName`, где `EventName` — имя обрабатываемого события. Каждое значение такой пропсы должно име
> насчет handleComponentNameEventName этого не совсем согласен, зачем прям отражать название компоненты? чаще всего из контекста понятно что это за модалка (если она одна) и поэтому достаточно написать handleModalClose вместо handleCreateReportModalClose

ну это для определенности, чтобы ты особо не думал и везде было единообразно и 100% очевидно, если мы здесь какой-то люфт оставляем то сразу же обсирелло может случиться из-за неправильной оценки

конкретно в твоем случае шо то шо это по большому счету, если честно

хотя бывают действительно случаи, когда конское название компоненты + конское название события дают в сумме конское название хэндлера, и оно правда избыточное как правило, тогда наверное имеет смысл отходить от этого

тут надо подумать и поискать конкретные хорошие примеры, я завтра думаю этим займусь и вернусь сюда еще раз подумаю

2019-11-14 08:08 UTC, in19farkt commented on JS/goodPractice.md
> +        * Пропсы react-компоненты, относящиеся к обработке событий, должны именоваться по шаблону `onEventName`, где `EventName` — имя обрабатываемого события. Каждое значение такой пропсы должно име
> Для модалки обычно желательно обернуть БЭМ-элементом, который охарактеризует предназначение модалки - модалка с авторизацией, например.

Не понял о чем тут и зачем так делать

2019-11-14 08:08 UTC, kinda-neat commented on JS/goodPractice.md
> +        * Пропсы react-компоненты, относящиеся к обработке событий, должны именоваться по шаблону `onEventName`, где `EventName` — имя обрабатываемого события. Каждое значение такой пропсы должно име
> насчет handleComponentNameEventName этого не совсем согласен, зачем прям отражать название компоненты? чаще всего из контекста понятно что это за модалка (если она одна) и поэтому достаточно написать handleModalClose вместо handleCreateReportModalClose

в примере так же показано использование правила через handleCreateReportModalClose, типа у меня компонента называется CreateReportModal

2019-11-14 08:08 UTC, chmnkh commented on JS/goodPractice.md
> +        * Обработчики событий на хост-узлах внутри компоненты (div, span и т.д.) должны именоваться по шаблону `onElementNameEventName`, где `ElementName` - имя БЭМ-элемента. Пример: `<div className=
если ты погуглишь, то увидишь в разных источниках по реакту термины типа host components, host tree, но насчет host node возможно не совсем корректно, и можно переписать, я согласен

2019-11-14 08:10 UTC, kinda-neat commented on JS/goodPractice.md
> +        * Обработчики событий на хост-узлах внутри компоненты (div, span и т.д.) должны именоваться по шаблону `onElementNameEventName`, где `ElementName` - имя БЭМ-элемента. Пример: `<div className=
я частенько одно время встречал, даже в доке реакта по-моему есть

2019-11-14 08:10 UTC, chmnkh commented on JS/goodPractice.md
> +        * Пропсы react-компоненты, относящиеся к обработке событий, должны именоваться по шаблону `onEventName`, где `EventName` — имя обрабатываемого события. Каждое значение такой пропсы должно име
@sk1e  дай пример кода плиз, чтобы я убедился, что так тебя понял

как должно быть по стандартам, в твоем понимании

2019-11-14 08:11 UTC, kinda-neat commented on JS/goodPractice.md
> +        * Обработчики событий на хост-узлах внутри компоненты (div, span и т.д.) должны именоваться по шаблону `onElementNameEventName`, где `ElementName` - имя БЭМ-элемента. Пример: `<div className=
![image](https://user-images.githubusercontent.com/27883524/68838374-09d41380-06f1-11ea-9c5f-42fafd522bfa.png)

2019-11-14 08:11 UTC, kinda-neat commented on JS/goodPractice.md
> +        * Обработчики событий на хост-узлах внутри компоненты (div, span и т.д.) должны именоваться по шаблону `onElementNameEventName`, где `ElementName` - имя БЭМ-элемента. Пример: `<div className=
https://github.com/reactjs/reactjs.org/search?utf8=%E2%9C%93&q=host&type=

2019-11-14 08:24 UTC, sk1e commented on JS/goodPractice.md
> +        * Обработчики событий на хост-узлах внутри компоненты (div, span и т.д.) должны именоваться по шаблону `onElementNameEventName`, где `ElementName` - имя БЭМ-элемента. Пример: `<div className=
это ортогональный и чересчур абстрактный термин. С ним ты усложняешь подачу информации. Мы рассмариваем элементы в разрезе БЭМ, и термин «БЭМ-элемент» подходит лучше

2019-11-14 08:28 UTC, sk1e commented on JS/goodPractice.md
> +        * Пропсы react-компоненты, относящиеся к обработке событий, должны именоваться по шаблону `onEventName`, где `EventName` — имя обрабатываемого события. Каждое значение такой пропсы должно име
> Не понял о чем тут и зачем так делать

Незачем) Мне подумалось, что может иметь смысл верстать по несколько модалок и делать обёртки для них. Но это не так.

2019-11-14 08:35 UTC, sk1e commented on JS/goodPractice.md
> +        * Пропсы react-компоненты, относящиеся к обработке событий, должны именоваться по шаблону `onEventName`, где `EventName` — имя обрабатываемого события. Каждое значение такой пропсы должно име
> @sk1e дай пример кода плиз, чтобы я убедился, что так тебя понял
> 
> как должно быть по стандартам, в твоем понимании

У тебя правильные примеры, только опиши лучше разделение случаев. Модалки не имеет смысла оборачивать БЭМ-элементом, но какой-нибудь инпут например имеет и нужно объяснить, что хэндлер компонента нужно именовать по БЭМ-элементу, который  оборачивает это компонент.

```
  <form className={b('form')()}>
    <div className={b('first-name-input')()}>
      <input onChange={this.handleFirstNameInputChange}/>
    </div>
    <div className={b('last-name-input')()}>
      <input onChange={this.handleLastNameInputChange}/>
    </div>
  </form>
```

2019-11-15 08:44 UTC, chmnkh commented on JS/goodPractice.md
> +        * Пропсы react-компоненты, относящиеся к обработке событий, должны именоваться по шаблону `onEventName`, где `EventName` — имя обрабатываемого события. Каждое значение такой пропсы должно име
> > @sk1e дай пример кода плиз, чтобы я убедился, что так тебя понял
> > как должно быть по стандартам, в твоем понимании
> 
> У тебя правильные примеры, только опиши лучше разделение случаев. Модалки не имеет смысла оборачивать БЭМ-элементом, но какой-нибудь инпут, например, имеет и нужно объяснить, что хэндлер компонента нужно именовать по БЭМ-элементу, который оборачивает этот компонент.
> 
> ```
>   <form className={b('form')}>
>     <div className={b('first-name-input')}>
>       <Input onChange={this.handleFirstNameInputChange}/>
>     </div>
>     <div className={b('last-name-input')}>
>       <Input onChange={this.handleLastNameInputChange}/>
>     </div>
>   </form>
> ```

кстати я вообще чото о таком явно не задумывался, нормальная тема да

2019-11-15 09:05 UTC, chmnkh commented on JS/goodPractice.md
> +        * Пропсы react-компоненты, относящиеся к обработке событий, должны именоваться по шаблону `onEventName`, где `EventName` — имя обрабатываемого события. Каждое значение такой пропсы должно име
> > зачем прям отражать название компоненты?
> 
> > поэтому достаточно написать handleModalClose
> 
> Ты тут по-моему путаешься в показаниях)) Спрашиваешь зачем отражать имя компоненты и тут же пишешь "достаточно написать handleModalClose", используя при этом название компоненты в имени обработчика. Поэтому для меня не понятно что в итоге ты имел ввиду

тут имелось в виду, что компонента называлась как-то в духе `MegaSuperModal`, но в хэндлере всего лишь `Modal`

2019-11-15 11:18 UTC, chmnkh commented
@sk1e @kinda-neat @in19farkt формулировки переписал чуть чуть, чекните еще раз плиз

2019-11-18 05:04 UTC, in19farkt commented on JS/goodPractice.md
> +          <div className="block__cancel-button" onClick={this.handleCancelButtonClick} />
давай тут div на button заменим

2019-11-18 05:04 UTC, in19farkt commented on JS/goodPractice.md
> +          Обоснование: именуя колбэки по такому шаблону, мы не будем тратить время на придумывание имени и всегда можем понять предназначение колбэка лишь посмотрев на его имя. Примечание: в случаях,
Может Обоснование и Примечание сделаем разными абзацами?

2019-11-18 05:11 UTC, kinda-neat commented on JS/goodPractice.md
> +          <div className="block__cancel-button" onClick={this.handleCancelButtonClick} />
диватоз

2019-11-18 05:18 UTC, kinda-neat commented on JS/goodPractice.md
> +          Обоснование: именуя колбэки по такому шаблону, мы не будем тратить время на придумывание имени и всегда можем понять предназначение колбэка лишь посмотрев на его имя. Примечание: в случаях,
мб ваще стоит вынести нейминг функций в отдельный файл как это сделано с переменными?
и будет в итоге вот так:
![image](https://user-images.githubusercontent.com/27883524/69026449-7acf4000-09fd-11ea-8012-ff473237dd56.png)

2019-11-18 05:35 UTC, in19farkt commented on JS/goodPractice.md
> +          <div className="block__cancel-button" onClick={this.handleCancelButtonClick} />
новое заболевание? можно как-то вылечить?

2019-11-18 05:36 UTC, kinda-neat commented on JS/goodPractice.md
> +          <div className="block__cancel-button" onClick={this.handleCancelButtonClick} />
на самом деле давно известное, мы просто не знали как оно называется, это как с паттернами :)

2019-11-18 05:37 UTC, kinda-neat commented on JS/goodPractice.md
> +          <div className="block__cancel-button" onClick={this.handleCancelButtonClick} />
вылечить можно так: отправляешь слушать кучу докладов от Макеева и бьешь по рукам при попытке вмерджить такое :)

2019-11-18 05:41 UTC, in19farkt commented on JS/goodPractice.md
> +          <div className="block__cancel-button" onClick={this.handleCancelButtonClick} />
а с паттернами ты про что? про Серегин "фабрикоз"? или про то что паттерны есть, их все применяют, но никто не знает как их звать?

2019-11-18 05:41 UTC, kinda-neat commented on JS/goodPractice.md
> +          <div className="block__cancel-button" onClick={this.handleCancelButtonClick} />
не не не) про второе

2019-11-18 10:19 UTC, chmnkh commented on JS/goodPractice.md
> +          Обоснование: именуя колбэки по такому шаблону, мы не будем тратить время на придумывание имени и всегда можем понять предназначение колбэка лишь посмотрев на его имя. Примечание: в случаях,
https://github.com/fullstack-development/front-end-best-practices/blob/change-handlers-convention/JS/goodPractice.md

2019-11-18 10:23 UTC, kinda-neat approved these changes

2019-11-18 10:33 UTC, in19farkt approved these changes

2019-11-18 11:00 UTC, chmnkh commented
@sk1e серега нужно твое авторитетное мнение

2019-11-18 11:31 UTC, sk1e approved these changes

2019-11-18 11:41 UTC, merged