add standard for z-index #68
fullstack-development/front-end-best-practices pull request #73
Opened 2021-08-06 08:35 UTC by NZMinusDev

2021-08-09 05:17 UTC, Znack approved these changes

2021-08-09 06:50 UTC, sk1e requested changes

2021-08-09 06:50 UTC, sk1e commented on CSS/README.md
> +  - 20-25 — для выезжающих меню, модалок и т.д. .
"и т.д." подразумевает что перечисление объединено по какому-то очевидному признаку, но мне например не особо понятно. Нужно привести этот признак, иначе правило не будет чётким и не будем понятно когда 10-19 а когда 20-25 использовать

2021-08-09 06:50 UTC, sk1e commented on CSS/README.md
> +  - компоненты, в которых значение свойства назначено случайно, не будут вызывать проблем при использовании, например: когда статическая подсказка какого-нибудь компонента имеет большее значение, чем
Не понял этот пункт. Почему не будет вызывать проблем при использовании? А если наоборот нужен меньше z-index у стороннего компонента?

2021-08-09 07:19 UTC, NZMinusDev commented on CSS/README.md
> +  - компоненты, в которых значение свойства назначено случайно, не будут вызывать проблем при использовании, например: когда статическая подсказка какого-нибудь компонента имеет большее значение, чем
Диапазона значений думаете будет недостаточно?

2021-08-09 07:24 UTC, NZMinusDev commented on CSS/README.md
> +  - 20-25 — для выезжающих меню, модалок и т.д. .
https://github.com/fullstack-development/front-end-best-practices/pull/73/commits/aee8191882d840a7d183d9ab5aa70d7f62dff524

2021-08-09 07:29 UTC, sk1e commented on CSS/README.md
> +  - компоненты, в которых значение свойства назначено случайно, не будут вызывать проблем при использовании, например: когда статическая подсказка какого-нибудь компонента имеет большее значение, чем
Не, мне непонятен сам пункт как мотивации и пример непонятен. Раскрой плз (давай на "ты" лучше :))

2021-08-09 07:55 UTC, NZMinusDev commented on CSS/README.md
> +  - компоненты, в которых значение свойства назначено случайно, не будут вызывать проблем при использовании, например: когда статическая подсказка какого-нибудь компонента имеет большее значение, чем
Не понимаю в чем неочевидность: если надо разместить элементы компонента в определенном порядке - используется необходимый порядок значений из диапазона, предназначенный для компонента. Если есть в компоненте элементы, которые выходят за границы компонента, но относятся к нему - используется следующий диапазон(10-19). Если надо уже сами компоненты как-то организовать на странице - используем диапазон, наносящийся к странице.

2021-08-09 08:15 UTC, sk1e commented on CSS/README.md
> +  - компоненты, в которых значение свойства назначено случайно, не будут вызывать проблем при использовании, например: когда статическая подсказка какого-нибудь компонента имеет большее значение, чем
Так, давай откатим назад. Мотивация это блок где рассказывается что есть некоторая проблема которую твой стандарт решает. Первые два блока мне понятны, третий непонятен. То что ты сейчас написал это ведь не объяснение мотивации, потому что там не описана проблема.

2021-08-09 08:19 UTC, sk1e commented on CSS/README.md
> +  - 20-25 — для выезжающих меню, модалок и т.д. .
Очень размыто на самом деле:

>  для элементов, расширяющих функциональность исходного компонента: всплывающие меню, подсказки;

Что такое расширение функциональности? Что такое исходный компонент?

> для элементов, относящихся к базовой структуре страницы или её специфичному функционалу: выезжающие меню, модальные окна.

Что такое базовая структура страницы? Что такое специфичный функционал базовой страницы? 

Важно понимать что я не пытаюсь цепляться к каким-то мелочам: на интуитивном уровне я вижу какую-то связь и логику, но стандартизация в программировании очень тонкая и хрупкая штука, стандарты должны быть максимально понятными и однозначными. Если они не будут такими то они будут приносить вред вместо пользы, когда человеку станет неочевидно какой индекс задавать исходя из стандартов, когда без стандарта он бы просто взял какое-то значение исходя из его текущих требований.  

В общем нужно очень аккуратно подходить в выбору слов в стандартах и выбирать наиболее понятные формулировки

2021-08-09 08:21 UTC, sk1e commented on CSS/README.md
> +  - 20-25 — для элементов, относящихся к базовой структуре страницы или её специфичному функционалу: выезжающие меню, модальные окна.
почему у выезжающих меню и модальных окон выше индекс? Нам ведь нужно подсказки и всплывающие меню поверх них показывать

2021-08-09 08:23 UTC, sk1e commented on CSS/README.md
> +  - 10-19 — для элементов, расширяющих функциональность исходного компонента: всплывающие меню, подсказки;
почему мы не можем иметь те же индексы 0-9 что и в пределах компонента? Зачем переусложнять?

2021-08-09 08:27 UTC, sk1e commented on CSS/README.md
> +  - не придется задумываться над тем, какое значение назначить свойству;
а есть ли проблема такая вообще? Индекс пару-тройку раз используется чтобы показать одно поверх другого

2021-08-09 08:30 UTC, NZMinusDev commented on CSS/README.md
> +  - 20-25 — для элементов, относящихся к базовой структуре страницы или её специфичному функционалу: выезжающие меню, модальные окна.
то есть когда у статичной подсказки ползунка слайдера подсказка будет видна(без самого слайдера) поверх модального окна - это лучше?

2021-08-09 08:31 UTC, NZMinusDev commented on CSS/README.md
> +  - 10-19 — для элементов, расширяющих функциональность исходного компонента: всплывающие меню, подсказки;
чтобы логически отделить элементы видимые сразу от тех, что могут заезжать на другие блоки

2021-08-09 08:33 UTC, NZMinusDev commented on CSS/README.md
> +  - не придется задумываться над тем, какое значение назначить свойству;
встречал пару раз неочевидные значения(`999`, `123456`) из разряда: "ну чтобы наверняка перекрыл "

2021-08-09 08:35 UTC, NZMinusDev commented on CSS/README.md
> +  - не придется задумываться над тем, какое значение назначить свойству;
Если разные разработчики создают компоненты: один модальное окно, другой - ползунки на слайдере накладывает. И им в лучшем случае придется договариваться, в худшем - будет неожиданное наложение

2021-08-09 08:39 UTC, NZMinusDev commented on CSS/README.md
> +  - 20-25 — для элементов, относящихся к базовой структуре страницы или её специфичному функционалу: выезжающие меню, модальные окна.
Или когда пункты навигационного меню можно открыть, хотя overlay модального окна должен не давать этого сделать

2021-08-09 09:01 UTC, sk1e commented on CSS/README.md
> +  - 20-25 — для элементов, относящихся к базовой структуре страницы или её специфичному функционалу: выезжающие меню, модальные окна.
> то есть когда у статичной подсказки ползунка слайдера подсказка будет видна(без самого слайдера) поверх модального окна - это лучше?

да, если слайдер в самой модалке находится. Или подсказка. Вообще, я все штуки которые выходят за компонент рендерю наружу, в body, потому что иначе нужно гарантировать чтобы у всей цепочки контейнеров был `overflow: visible` чтобы показать этот компонент, а это накладывает серьёзные ограчения. 

А у тебя видимо это стандарт подразумевающий что это всё структурно внутри рендерится но визуально находится снаружи. Мне кажется это худшая стратегия из за той необходимости `overflow: visible`

2021-08-09 09:49 UTC, NZMinusDev commented on CSS/README.md
> +  - 20-25 — для элементов, относящихся к базовой структуре страницы или её специфичному функционалу: выезжающие меню, модальные окна.
А в чем собственно проблема? `z-index` же учитывает контекст наложения. С `overflow: visible` проблемой не сталкивался, потому что обычно такие штуки решал через абсолютное позиционирование.

2021-08-09 10:41 UTC, sk1e commented on CSS/README.md
> +  - 20-25 — для элементов, относящихся к базовой структуре страницы или её специфичному функционалу: выезжающие меню, модальные окна.
> С overflow: visible проблемой не сталкивался, потому что обычно такие штуки решал через абсолютное позиционирование.

какие штуки? Проблема в том что нужны гарантии `overflow: visible` у всех контейнеров за рамки которого выходит твой абсолютно спозиционированный компонент. Я тоже через абсолютное позиционирание решаю, просто рендерю в body через портал. С таким подходом мне твой стандарт с индексами не подойдёт

2021-08-10 06:38 UTC, NZMinusDev commented on CSS/README.md
> +  - не придется задумываться над тем, какое значение назначить свойству;
Набросал примеров проблем, которые могут возникнуть: [playground](https://codesandbox.io/s/black-breeze-cbytn?file=/style.css)

2021-08-10 14:54 UTC, NZMinusDev commented on CSS/README.md
> +  - 20-25 — для элементов, относящихся к базовой структуре страницы или её специфичному функционалу: выезжающие меню, модальные окна.
Спасибо большое за подробное пояснение. Из-за недостатка опыта не сразу сообразил о чем шла речь, что можно так реализовывать компонент. Следует ли добавить дополнительный пункт, описывающий данный случай и решение или стандарт тогда становится переусложненным и приносящим больше вреда?

2021-08-10 19:32 UTC, NZMinusDev commented on CSS/README.md
> +  - 20-25 — для элементов, относящихся к базовой структуре страницы или её специфичному функционалу: выезжающие меню, модальные окна.
Порталы используешь даже для таких элементов как: _dropdown пункты навигационного меню_ у header? А если не используется React - добавляешь скрипты для позиционирования?

2021-08-11 04:08 UTC, sk1e commented on CSS/README.md
> +  - 20-25 — для элементов, относящихся к базовой структуре страницы или её специфичному функционалу: выезжающие меню, модальные окна.
>  если не используется React - добавляешь скрипты для позиционирования?

Ну я слава богу всегда использую реакт, поэтому не скажу тут.

> Порталы используешь даже для таких элементов как: dropdown пункты навигационного меню у header?

Для этого скорее всего не стал бы через порталы делать. Портал нужен для низкоуровневых компонентов, элементы которых выходят за свою область типа всплывающей подсказки или всплывающего списка чтобы они всегда гарантированно показывались поверх остального. Эти элементы перестанут показываться если их вставить в край какой-нибудь таблицы с `overflow: auto`  который нужен для скрола таблицы, или в край карусели с `overflow: hidden` который нужен для скрытия соседних слайдов.

Мне кажется что для стандарта тут слишком сложно, неполно и размыто получится. Тут получатся размытые категории для стандартизации, потому что могут быть разные контексты требований. На первый взгляд можно выделить такие категории:

1. категория верхнеуровневых компонентов типа того же навигационного меню для которых можем гарантировать что контекст этих компонентов не сломает отображение меню;
2. категория низкоуровневых компонентов, у которых есть элементы с контекстом наложения и которые не выходят за границы компонента;
3. категория низкоуровневых компонентов у которых есть элементы с контекстом наложения и которые выходят за границы компонента.. Это те которые я через портал делаю.

Но нужно будет учитывать что, например, 3-ю категорию можно разными способами реализовать. Можно рендерить без порталов, но с применением алгоритма по поиску координат куда можно спозиционировать блок так чтобы он был виден. Для разных способов нужен будет разный подход к заданию индексов.

Ещё нужно учитывать что многие абсолютно спозиционированные элементы не должны показываться одновременно и соответственно их индексы не должны учитывать друг друга.

Мне кажется должны быть другие категории которые не описаны. Если человек возьмёт этот стандарт для такой категории, то он ему наоборот помешает, т.к. не решит проблемы и индексы заданные по стандарту не будут удовлетворять требованиям к результату, человек начнёт сомневаться что он правильно понял стандарт, прочитает ещё раз, начнёт спрашивать других, и всё это в конечном итоге займёт много времени. 

Я думаю тут лучше бы подошёл формат статьи или доклада где ты бы описал проблему и способ её решения, такой формат был бы более понятен другим для восприятия и необязателен для случаев когда он не подходит. Потом люди бы могли перенять эту практику и ссылаться на статью или доклад когда считали бы что такой вариант решения хорошо подходит в их случае.

2021-08-11 06:11 UTC, NZMinusDev commented on CSS/README.md
> +  - 20-25 — для элементов, относящихся к базовой структуре страницы или её специфичному функционалу: выезжающие меню, модальные окна.
Можешь, пожалуйста, привести пример категории/случая, который не вписывается в следующий алгоритм для z-index(для представленных тобой категорий будет следующее соответствие: 1 -> 10-19, 2 -> (-9)-9, 3 -> 30-39): 
  - диапазон < -9 для компонентов, которые должны быть ниже любых других;
  - диапазон (-9)-9 для компоновки собственных элементов компонента, не выходящих за его пределы: наложение текста в картинках, range элементы range-slider-а;
  - диапазон 10-19 для элементов компонентов, которые могут выходить за границы компонента или своего родителя, причем компонент сам по себе не предназначен для перекрытия других компонентов и есть гарантия что у всей цепочки контейнеров `overflow: visible`: задуманные по дизайну декоративные элементы являющиеся частью блока позволяющие создать эффект не прямоугольной формы, всплывающие списки header-a;
  - диапазон 20-29 для компонентов, которые сами по себе должны находиться выше других компонентов: модальные окна, выезжающие из вне viewport меню;
  - диапазон 30-39 для элементов компонентов, которые могут выходить за границы компонента или своего родителя, причем компонент сам по себе может быть как из диапазона (-9)-9, так и 30-39: подсказки для компонентов, календарь, dropdown список.

Стандарт больше рассчитан не на 100%-е определение конкретного значения z-index в каждом локальном случае, а на логическое разделение элементов на слои(диапазоны, из которых уже можно выбирать значения исходя из ситуации) - такое разделение должно помочь избежать проблем, когда из-за несогласованности разработчиков происходит неожиданное наложение из разных по категории элементов + когда выбор ограничен диапазоном, а не всеми доступными числами - проще выбирать и меньше путаница при росте количества компонентов. 

Для написания статьи потребуется больше опыта, чтобы рассмотреть максимальное количество случаев, встречающихся в практике.

В случае если встретится какая-то неочевидная ситуация, то можно оформить новое issue и расширить стандарт на его основе. Да, это потенциально может добавить дополнительные трудозатраты в будущем(а может и не добавить), но проблем из-за общей несогласованности значений свойства в проекте больше, чем когда для 1 из разработчиков стандарт не подойдет под какой-нибудь unique случай.

2021-08-11 06:52 UTC, sk1e commented on CSS/README.md
> +  - 20-25 — для элементов, относящихся к базовой структуре страницы или её специфичному функционалу: выезжающие меню, модальные окна.
> Можешь, пожалуйста, привести пример категории/случая, который не вписывается в следующий алгоритм для z-index(для представленных тобой категорий будет следующее соответствие: 1 -> 10-19, 2 -> (-9)-9, 3 -> 30-39):

Нет, мне сложно представить все случаи, просто предпологаю что они есть.

> Стандарт больше рассчитан не на 100%-е определение конкретного значения z-index в каждом локальном случае, а на логическое разделение элементов на слои

Это уже не стандарт, а практика. Стандарт это штука которой должен соответствовать каждый проект, мне видится что далеко не каждому проекту он подойдёт, потому что, опять же, разные контексты. Если он не подойдёт то начнутся проблемы. Ты можешь гарантировать что из-за него не возникнет проблем? 

>  но проблем из-за общей несогласованности значений свойства в проекте больше, чем когда для 1 из разработчиков стандарт не подойдет под какой-нибудь unique случай.

у меня вообще никогда не было проблем с индексами.  В общем  я против этого в стандартах. Если остальные находят это суперполезным - пожалуйста, добавляйте.

2021-08-13 05:06 UTC, closed without merging