Js block
fullstack-development/front-end-best-practices pull request #9
Opened 2019-04-03 07:41 UTC by krashaen

2019-04-03 07:57 UTC, NikitaRzm requested changes

2019-04-03 07:57 UTC, NikitaRzm commented on JS/README.md
> +    > В сафари если включен режим инкогнито или если в браузере стоит блокировка `cookie`, то браузер будет райзить ошибку. Поэтому если ее не отловить, приложение посыпется :)
Сюда можно дописать: работа со службами браузера (navigator services, cookie, localStorage), т.к. это внешние по отношению к нашему коду службы, от которых не ясно, чего ждать. На спеки тут полагаться не стоит, т.к. есть и новые движки, которые имеют в том числе баги в своих сорцах.

2019-04-03 07:57 UTC, NikitaRzm commented on JS/architecture.md
> +    > В рамках одного модуля описывать только схожий функционал, который объединен смыслом. Это называется [связность](https://ru.wikipedia.org/wiki/%D0%A1%D0%B2%D1%8F%D0%B7%D0%BD%D0%BE%D1%81%D1%82%D
Например, в статистике сегмантация выполняется по таким же принципам...

2019-04-03 07:57 UTC, NikitaRzm commented on JS/jQuery.md
> +    > Это позволит легко отсоединять обработчики, когда они перестанут быть нужны.
"когда необходимость в них закончится", "когда нужда в них отпадет", "когда они станут ненужными"

2019-04-03 07:57 UTC, NikitaRzm commented on JS/libraries.md
> +    > Если используюься дополнительные модули, то в package.json должны быть прописаны пути до локальных модулей, которые вы установили.
используюься

2019-04-03 07:57 UTC, NikitaRzm commented on JS/react.md
> +Читать и применять только если уже знакомы с React, в противном случае можно пока игнорить
Оформи заголовком или сноской)

2019-04-03 08:28 UTC, NikitaRzm requested changes

2019-04-03 08:28 UTC, NikitaRzm commented on JS/README.md
> +6. **Вся работа со службами браузера (`navigator services`, `cookie`, `localStorage`), т.к. это внешние по отношению к нашему коду службы, от которых не ясно, чего ждать. На спеки тут полагаться не с
Тут предложение не связано, "Вся рабоат со службами (что-то), т.к.

2019-04-03 08:28 UTC, NikitaRzm commented on JS/performance.md
> +    > В зависимости от типа и сложности css-селектора зависит производительность рендеринга и анимации сайта. Например использование в `transition` селектора по атрибуту (например `input[type="text"]
DOM-деревл

2019-04-03 08:28 UTC, NikitaRzm commented on JS/variables.md
> +3. **При именовании переменных использовать `camelCase`, так как это принято в JavaScript комьюнити**;
Тут оговорить сразу тонкий момент может быт ьможно - типа если с бэка приходит снейккейс или любой другой - имеет смысл нормализовать ключи для консистентности ?)

2019-04-03 08:45 UTC, Znack requested changes

2019-04-03 08:45 UTC, Znack commented on JS/README.md
> +    > * [browsersec](https://code.google.com/archive/p/browsersec/wikis/Main.wiki);
тут лучше назвать `Browser Security Handbook from Google`

2019-04-03 08:45 UTC, Znack commented on JS/README.md
> +    > * [html5sec](https://html5sec.org/#javascript);
А это `HTML5 Security Cheatsheet` :)

2019-04-03 08:45 UTC, Znack commented on JS/README.md
> +    > * [html5sec](https://html5sec.org/#javascript);
заходи на страницы и прямо оттуда тайтлы бери, я так всегда делаю, иногла уточняю, как в случае выше добавил `from Google`

2019-04-03 08:45 UTC, Znack commented on JS/README.md
> +    > * [Web Security Basics](https://github.com/vasanthk/web-security-basics).
подсписок лучше без цитат сделать, это же просто вложенные пункты, не описание

2019-04-03 08:45 UTC, Znack commented on JS/architecture.md
> +    >  var box = {};
тут добавить коммент, что это пример плохого кода
```javascript
    > // bad code
    >  var box = {};
```

2019-04-03 08:45 UTC, Znack commented on JS/architecture.md
> +    > constructor (name) {
поехал отступ

2019-04-03 08:45 UTC, Znack commented on JS/variables.md
> +1. **Имя переменной должно полно и точно описывать сущность и ее предназначение**;
лучше переименовать файл в naming.md

2019-04-03 09:41 UTC, chmnkh requested changes

2019-04-03 09:41 UTC, chmnkh commented on JS/README.md
> +    > * Это непрофессионально и при ревью кода опытными разработчиками такие хаки будут очень остро критиковаться;
на мой взгляд, такие аргументы как "это непрофессионально" - это ни о чем

выглядит, как будто "это зашквар - не надо так писать, а то тебя затроллят" без обоснований, т.е. я бы не стал отдельным пунктом в аргументации для правила писать что-то подобное

2019-04-03 09:41 UTC, chmnkh commented on JS/README.md
> +    > Любое решение в первую очередь должно быть понятным и разбитым на логичные части, чтобы другие члены команды могли разобраться не только в назначении кода, но и во применяемых решениях без допо
"в**о** применяемых" - как-то не по-русски вроде как)

2019-04-03 09:41 UTC, chmnkh commented on JS/README.md
> +    > Иногда на проекте могут возникнуть задачи, решая которые вы делаете систему уязвимой в плане падения, а не взлома. Пример из реальной жизни - подсчет суммы заказа на клиенте. Так как любым расч
случаи падени**й** (или падени**я**?) наверное, а не падени**и**

2019-04-03 09:41 UTC, chmnkh commented on JS/architecture.md
> +    > Для каждого модуля - только один файл. Без использования webpack и других сборщиках сами заботьтесь о том, чтобы не загрязнять глобальную область видимости (оборачивать все содержимое каждого ф
сборщик**ов**

2019-04-03 09:41 UTC, chmnkh commented on JS/architecture.md
> +    > В рамках одного модуля описывать только схожий функционал, который объединен смыслом. Это называется [связность](https://ru.wikipedia.org/wiki/%D0%A1%D0%B2%D1%8F%D0%B7%D0%BD%D0%BE%D1%81%D1%82%D
а между модулями было максимально**е** различие

2019-04-03 09:41 UTC, chmnkh commented on JS/architecture.md
> +5. **При написании класса все публичные методы объявляйте первыми, причем самым первым должен идти конструктор, все частные методы группируйте по смыслу внизу класса**;
частный метод - есть такой термин?

2019-04-03 09:41 UTC, chmnkh commented on JS/goodPractice.md
> +    > Объявление переменной, должно быть рядом с ее использованием. Это дает более быстрое понимание того, что происходит в коде, плюс снижается вероятность неправильного использования переменной или
> Объявление переменной, должно быть рядом с ее использованием.

1. Запятая не нужна
2. должно быть рядом с **местом ее использования** было бы корректнее сказать

2019-04-03 09:41 UTC, chmnkh commented on JS/goodPractice.md
> +6. **Все кнопки сабмита должны быть внутри `<form>` вместе со всеми соответсвующими инпутами и обработку завершения заполнения вешать на событие `submit` формы, а не клик по кнопке**;
Я бы это на 2 предложения разделил:

Все кнопки сабмита должны быть внутри `<form>` вместе со всеми соответсвующими инпутами.  Обработку завершения заполнения следует вешать на событие `submit` формы, а не на клик по кнопке.

Текущее предложение коряво читается как-то

2019-04-03 09:41 UTC, chmnkh commented on JS/goodPractice.md
> +9. **Не изменять прототипы стандартных конструкторов (String.prototype или Function.prototype), до тех пор пока вопрос внимательно не изучен и этот трюк не согласован со страшим разработчиком**;
Я бы перед примерами прототипов написал "например, ", потому что без этого может сложиться впечатление что правило только к перечисленными прототипам относится

2019-04-03 09:41 UTC, chmnkh commented on JS/goodPractice.md
> +      `EventName` — имя обрабатываемого события. Каждое значение атрибута должно именоваться по шаблону `handle[ElementName]EventName`.
я бы это правило переписал таким образом, чтобы мы могли его давать в том числе стажерам
для этого я бы написал сначала про хэндлеры (чтобы стажеры читали этот пункт и не парились, читая про пропсы чото) а потом про пропсы
плюс я немного фиксанул (как мне кажется) описание `ElementName`, дописав, что это может быть и блоком (иногда на блок хэндлеры вешаются, ты не напишешь ведь просто handleClick), а опускать `ElementName` можно только в имени пропсы.

т.е. сделал бы типа такого:

Соглашение об именованиях:
* Обработчики событий должны именоваться по шаблону `handle[ElementName]EventName`, 
где `ElementName` — имя БЭМ-блока/элемента; `EventName` — имя обрабатываемого события.
* В react-компоненте, атрибуты пропсов, относящиеся к обработке событий компонента, должны именоваться по шаблону `on[ElementName]EventName`. Если пропса относится к событию на блоке, то [ElementName] в названии данной пропсы опускается.

Призываю @sk1e на одобрение, потому что его правило.

2019-04-03 09:41 UTC, chmnkh commented on JS/goodPractice.md
> +      * Имя метода должно быть декларативным (из названия должно быть понятно для чего нужен метод и что он делает не задумываясь о его внутренней реализации).
1. а точно корректно называть имя "декларативным"?
2. то что в скобках я бы переформулировал, потому что сейчас как будто метод делает что-то, не задумываясь о своей внутренней реализации)

2019-04-03 09:41 UTC, chmnkh commented on JS/goodPractice.md
> +      * Если в метод необходимо передать много параметров, объединяйте их в один объект. Например у вас есть метод который рисует прямоугольник принимая координаты точек, ширину, высоту, цвет, толщин
После "Например" запятая, после "метод" запятая, перед "принимая" запятая.
После "другие" - нужно дописать "параметры".
После "В таком случае" запятая. После "Все параметры" запятая. После "Их порядок" запятая. 
"и позволит удобно сделать многие свойства с дефолтными значениями" - не понятно зачем нужно, мы же и без объекта можем дефолты задавать.

2019-04-03 09:41 UTC, chmnkh commented on JS/goodPractice.md
> +      * В случае объекта параметров для наглядности можно использовать деструктуризацию;
"В случае объекта параметров" => "В случае, когда параметры передаются объектом,"
"для наглядности" - не совсем понятно что это вообще значит. я бы написал что-то типа "получать их значения предпочтительнее с помощью деструктуризации". Ну и мб бахнул бы пример как надо и как не надо, чтобы было видно, что деструктуризация - это приятный сахар.

2019-04-03 09:41 UTC, chmnkh commented on JS/goodPractice.md
> +      * Соблюдать принцип Single Responsibility. Метод должен выполнять только одну задачу (Например, метод `createReport`, который создает отчет и отправляет его на сервер необходимо разделить на дв
не понятно, почему Например с большой буквы здесь

\+ я бы дописал, чтобы вопросов не возникало:

> разделить на два: `createReport` и `sendReport`

2019-04-03 09:41 UTC, chmnkh commented on JS/goodPractice.md
> +      * Метод должен быть компактным. Обычно, длина метода варьируется в пределах 10-40 строк. Это не значит что ваш метод обязательно должен должен быть в таких рамках, но если ваш метод занимает 20
это повод **задуматься о том,**

2019-04-03 09:41 UTC, chmnkh commented on JS/goodPractice.md
> +    >      elem.addEventListener( "click" , this.greet);
я бы в примерах кода тоже нашим стандартам следовал.

тут написан пример по стандарту с именованием хэндлеров Сереги Черепанова, но его сейчас убрали и надо бы по идее переписать под стандарт текущий (Сереги Петрова)

2019-04-03 09:41 UTC, chmnkh commented on JS/goodPractice.md
> +    >  $(this).click(function(event) {  // не называйте просто "e", пишите "event"
тут бы я тоже тоже не юзал анонимные функции а сразу примеры с хэндлерами рассматривал, чтоыб стандартам соответствовать

т.е. можно в примере написать сразу код нормально названных методов хэндлеров, а не код с навешиванием обработчиков

2019-04-03 11:07 UTC, krashaen commented on JS/README.md
> +    > * Это непрофессионально и при ревью кода опытными разработчиками такие хаки будут очень остро критиковаться;
По мне норм, @Znack что думаешь?

2019-04-03 11:09 UTC, krashaen commented on JS/goodPractice.md
> +      `EventName` — имя обрабатываемого события. Каждое значение атрибута должно именоваться по шаблону `handle[ElementName]EventName`.
@sk1e, явись)

2019-04-03 11:50 UTC, sk1e commented on JS/goodPractice.md
> +      `EventName` — имя обрабатываемого события. Каждое значение атрибута должно именоваться по шаблону `handle[ElementName]EventName`.
> ты не напишешь ведь просто handleClick

Ну я задумывал это так что напишу именно так, типа из контекста понятно что это хэндлер клика по всему блоку/компоненту

2019-04-03 11:53 UTC, krashaen commented on JS/goodPractice.md
> +    >      elem.addEventListener( "click" , this.greet);
class Component {

        bindEvents () {
            elem.addEventListener( "click" , this.onElementClick);
        }

        onElementClick () {
            // это самодостаточная функция, которую мы можем в других местах легко использовать, у нее есть имя, так что легче будет понять ее назначение и смысл.
            alert('Спасибо!');
        }
    }

Так норм?

2019-04-03 11:55 UTC, krashaen commented on JS/goodPractice.md
> +    >  $(this).click(function(event) {  // не называйте просто "e", пишите "event"
тут чет не догнал как должно выглядеть(

2019-04-03 11:56 UTC, krashaen commented on JS/goodPractice.md
> +      `EventName` — имя обрабатываемого события. Каждое значение атрибута должно именоваться по шаблону `handle[ElementName]EventName`.
оставляем так как есть?

2019-04-03 12:06 UTC, sk1e commented on JS/goodPractice.md
> +      `EventName` — имя обрабатываемого события. Каждое значение атрибута должно именоваться по шаблону `handle[ElementName]EventName`.
Хотя думаю так лучше, только в handle[ElementName]EventName квадратные скобки обозначают опциональную часть. Там часть неопциональна, поэтому нужно убрать скобки.

И в этой части 
> то [ElementName] в названии данной пропсы опускается.

тоже убрать скобки, потому что термом выступает ElementName, а скобки это синтаксис формального описания. На mdn похожий синтаксис для css

2019-04-03 12:20 UTC, sk1e commented on JS/naming.md
> +    > Как правило, чтобы раскрыть смысл переменной, достаточно около трех слов (10-15 символов). Переменные всегда используются в каком-то контексте, исходя из которого некоторые детали могут опускат
Может лучше обрезать длинные строки?  Есть вероятность что в других редакторах/гит-хостингах с этим будет неудобно работать.

2019-04-03 12:20 UTC, sk1e commented on JS/goodPractice.md
> +    > Не полагаться на this при работе с объектами событий, а использовать первый параметр коллбека event.
почему описание стандарта цитатами оформлено? Они тусклые, их хуже видно. Не лучше ли заголовки сделать побольше?

2019-04-03 14:02 UTC, Znack commented on JS/goodPractice.md
> +    >  $(this).click(function(event) {  // не называйте просто "e", пишите "event"
`function(event) {` скорее всего Леха имеет ввиду надо не прямо там объявлять, где передаем в `click`, а в отдельном месте, потмоу что у нас по-хорошему надо отдельно функции объявлять, и отдельно их колбеками передавать :)

2019-04-03 14:04 UTC, Znack commented on JS/README.md
> +    > * Это непрофессионально и при ревью кода опытными разработчиками такие хаки будут очень остро критиковаться;
Ну Леха в чем-то прав, лучше явно написать, что это тупо будет быстрее работать, почти наверняка надежней, и почти наверняка проще читаться и исправляться. Если на HTML+CSS только с помощью хаков можно извратиться для реализации, вот тогда уже на JS стоит все-таки переходить, чтобы поддерживаемость проекта не падала, это еще тоже добавить по хорошему надо.

2019-04-03 14:04 UTC, Znack commented on JS/naming.md
> +    > Как правило, чтобы раскрыть смысл переменной, достаточно около трех слов (10-15 символов). Переменные всегда используются в каком-то контексте, исходя из которого некоторые детали могут опускат
Так это же абзац, все параграфы тупо как строка идут, тут точками предоожения разделены. Так все доки пишутся, должно быть норм :)

2019-04-03 14:05 UTC, Znack commented on JS/goodPractice.md
> +    > Не полагаться на this при работе с объектами событий, а использовать первый параметр коллбека event.
Это в прошлых ПР-ах обсуждали, пока оставляем как есть, потом отдельным ПР-ом изменим, если надо будет :)

2019-04-03 14:16 UTC, sk1e commented on JS/naming.md
> +    > Как правило, чтобы раскрыть смысл переменной, достаточно около трех слов (10-15 символов). Переменные всегда используются в каком-то контексте, исходя из которого некоторые детали могут опускат
Форматированный текст симпатичней выглядит в редакторе. Но если все так пишут, штош поделаешь

2019-04-03 14:35 UTC, Znack requested changes

2019-04-03 14:35 UTC, Znack commented on JS/README.md
> +    > * Это непрофессионально и при ревью кода опытными разработчиками такие хаки будут очень остро критиковаться;
я бы пункт про читаемость поднял над этим, а тут упомянул, что только не противоречить предыдущему пункту :)

2019-04-03 14:35 UTC, Znack commented on JS/README.md
> +4. **Не подключать скрипты с удаленных источников - только с наших серверов**;
вот это кстати странное правило, не знаю зачем оно, может убрать его? @krashaen @NikitaRzm @sk1e @chmnkh

2019-04-03 14:35 UTC, Znack commented on JS/README.md
> +5. **Все js-ки подключаем внизу страницы перед закрывающимся тегом `<body>`**;
это предлагаю в произвордительность перенести

2019-04-03 14:35 UTC, Znack commented on JS/README.md
> +6. **Вся работа со службами браузера (`navigator services`, `cookie`, `localStorage`) должна быть обернута в try/catch, т.к. это внешние по отношению к нашему коду службы, от которых не ясно, чего жд
это предлагаю в хорошие практики перенести :)

2019-04-03 14:35 UTC, Znack commented on JS/goodPractice.md
> +      * Имя метода должно быть `self description`(Описывать сам себя). Из названия должно быть понятно для чего нужен метод и что он делает. Не должно быть причин задумываться о его внутренней реализ
`self descriptive`

2019-04-03 14:35 UTC, Znack commented on JS/goodPractice.md
> +    >  $(this).click(function(event) {  // не называйте просто "e", пишите "event"
Нашел, это про 11-ое правило из этого же блока Леха имел ввиду :)

2019-04-03 14:35 UTC, Znack commented on JS/goodPractice.md
> +    >  if (status === constants.ACTIVE_STATUS) {...}
`if (status === ordersModule.ACTIVE_STATUS) {...} `

а то блок constants как-то тоже не очень название :)

2019-04-03 14:35 UTC, Znack commented on JS/goodPractice.md
> +    >    window.foo = 'hello world';  // обратить внимание, что переменная создана без var, значит она глобальная
`// обратить внимание, что переменная создана без var, значит она глобальная` — злесь этот коммент уже надо убрать :)

2019-04-03 14:35 UTC, Znack commented on JS/goodPractice.md
> +22. **Всегда следует добавлять и удалять классы у DOM-элементов, а не изменять конкретные свойства css у элементов**;
иногда это правило невозможно соблюсти, надо бы его ослабить как-нибудь. Как нибудь так:

```
Все изменения в стилях, которые можно сделать через переключение классов у элемента, надо делать через добавление/удаление классов, а не простановку стилей у DOM-элементов. Так, например, можно переключать видимость элемента. Однако для непрерывно изменяющихся численных значений так сделать уже не получится, как например при изменении свойства `top` при скролле страницы, поэтому тут придётся все-таки проставлять напрямую у элемента значение в css-свойстве.
```

2019-04-03 14:35 UTC, Znack commented on JS/jQuery.md
> +  $lists.append($newList);
какой тут странный пример :) Ищем все ul и добавляем туда ul :) давай лучше так 

```javascript
  var $newMessage = $('<li class="message" />');
  var $messageList = $body.find('ul.messages');
  $messageList.append($newMessage);
```

2019-04-03 14:35 UTC, Znack commented on JS/jQuery.md
> +    > * Выше было требование, что все обработчики должны быть отименованы. Тут это принимает еще более строгий характер — имена обработчиков для разных инстансов одного и того же класса должны быть у
в конце лучше переформулировать на `а то неожиданно для разработчика отключит сразу для всех слайдеров на странице`

2019-04-03 14:35 UTC, Znack commented on JS/naming.md
> +    >    const [, city, zipCode] = address.match(cityZipCodeRegex) || [];
тут невалидная конструкция деструктуризации в примере :)

2019-04-03 14:39 UTC, krashaen commented on JS/naming.md
> +    >    const [, city, zipCode] = address.match(cityZipCodeRegex) || [];
почему? 
![image](https://user-images.githubusercontent.com/12808495/55487795-fd66e300-5658-11e9-878d-3409270d2248.png)

2019-04-03 14:44 UTC, Znack commented on JS/naming.md
> +    >    const [, city, zipCode] = address.match(cityZipCodeRegex) || [];
А я нижнее подчеркивание использовал 😆

2019-04-03 16:16 UTC, Zarwlar commented on JS/jQuery.md
> +    > * Также классы позволяют сделать структуру всех блоков одинаковой и предсказуемой — зная, как устроен блок slider, уже можно предсказать, как устроены блоки calendar  и dropdown. У всех у них б
Двойной пробел)
> calendar  и

2019-04-03 16:25 UTC, Zarwlar commented on JS/libraries.md
> +    > * есть ли у нее отдельный публичный репозиторий и где он находится;
Стоит добавить пункт про то, как сопровождается либа:

> Обратить внимание, сопровождается ли библиотека, или является заброшенной. Есть ли pull request'ы, и есть ли в них обсуждения. Принимаются ли pull request'ы?

Соблюдение этого правила поможет избежать головной боли, если с библиотекой возникнут проблемы, и появится необходимость коммуницировать с третьеми лицами — разрабами либы. Хотя бы будет с кем поговорить :)

2019-04-03 16:32 UTC, Zarwlar commented on JS/libraries.md
> +    > * если доков нет или нет нормального описания, надо внимательно изучить код библиотеки и понять API, которое позволит решить проблему;
Стоит добавить правило про тесты:

> Обратить внимание, протестирована ли библиотека. Если библиотека протестирована, то стоит уделить внимание тестам, которые были написаны для неё: какие use-cases покрываются в тестах, и решают ли эти use-cases проблемы, ради которых вы хотите её использовать. Так же стоит уделить внимание к качеству самих тестов, не являются ли они хрупкими к изменениям и т.д. Если к рассматриваемой библиотеке тестов нет, возможно, вам стоит поискать другую библиотеку

2019-04-03 16:36 UTC, Zarwlar commented on JS/performance.md
> +1. **Еще раз: В проектах на jquery или чем-либо, где поиск DOM-элементов идет по селекторам - надо кэшировать все найденные элементы**;
А зачем об этом написано ещё раз? :)

2019-04-03 16:44 UTC, Zarwlar commented on JS/react.md
> +    > * Асинхронные `action creator` делать только с тремя `dispatch` и только для того, чтобы показать состояния одного процесса. То есть диспатчить сначала старт запроса, потом его завершение успеш
Не понял эту фразу:

> А делать сразу три запроса и диспатчить только три `action`

Она как будто противопоставляется тому, как нужно организовывать асинхронный action creator, но мне не ясно это противопоставление. Т.е. в чём мой вопрос: о каких _сразушных_ трёх запросах идёт речь в этом предложении?)

2019-04-03 17:00 UTC, Zarwlar commented on JS/react.md
> +    >        <div>Order status: {this.renderStatusView(this.props.status)}</div>
Или здесь, или не здесь, а ниже, или в вообще в другом топике, но мне кажется, что стоит написать про render methods stateful component. Их использование оправдано только в том случае, если возвращаемый из метода кусок jsx действительно является неотъемлемой частью компоненты. В противном случае, лучше создать новую stateless компоненту и перенести код туда. Тем самым мы поддерживаем [идиоматику](https://reactjs.org/docs/thinking-in-react.html) реакта. @NikitaRzm Никит, скажешь что-нибудь по этому поводу?)

2019-04-03 17:22 UTC, Zarwlar commented on JS/goodPractice.md
> +      * Имя метода должно быть `self description`(Описывать сам себя). Из названия должно быть понятно для чего нужен метод и что он делает. Не должно быть причин задумываться о его внутренней реализ
'Описывать сам себя' -> 'Описывать само себя' Речь идёт об имени, а оно среднего рода :)

2019-04-04 03:15 UTC, chmnkh commented on JS/goodPractice.md
> +    >      elem.addEventListener( "click" , this.greet);
```
    bindEvents() {
        stopButton.addEventListener( 'click' , this.handleStopButtonClick);
    }

    handleStopButtonClick() {
        ...
    }
```

уот так уот я бы вставил

2019-04-04 03:20 UTC, chmnkh commented on JS/README.md
> +4. **Не подключать скрипты с удаленных источников - только с наших серверов**;
мне кажется правило действительно странное и оно кругом и всюду нарушается + смущает стажеров)
то что не стоит какие-то левые скрипты не понять откуда подключать вроде бы достаточно очевидно

2019-04-04 03:21 UTC, chmnkh commented on JS/goodPractice.md
> +      * Имя метода должно быть `self description`(Описывать сам себя). Из названия должно быть понятно для чего нужен метод и что он делает. Не должно быть причин задумываться о его внутренней реализ
> 'Описывать сам себя' -> 'Описывать само себя' Речь идёт об имени, а оно среднего рода :)

еще и с маленькой буквы написать надо тащемта

2019-04-04 04:28 UTC, chmnkh commented on JS/goodPractice.md
> +    >  $(this).click(function(event) {  // не называйте просто "e", пишите "event"
Чото типа такого я имел в виду
```
Плохо:
handleButtonClick() {
  const buttonWidth = $(this).width();
  ...
}

Хорошо:
handleButtonClick(event) {
  const buttonWidth = $(event.currentTarget).width();
  ...
}
```
Т.е. сейчас пример с биндингом хэндлеров не по стандарту сделан (вдобавок к анонимным функциям там еще и `buttonWidth` с долларом зачем-то и `let`)
Чтобы это было по стандарту надо хэндлеры в отдельные методы выносить, но тогда впринципе смысла в биндинге в примере нету, поэтому можно только сами хэндлеры в качестве примера показать.

2019-04-04 04:33 UTC, chmnkh commented on JS/goodPractice.md
> +23. **Очень полезно понимать, как работают циклы перерисовки браузера и как можно проверить и увеличить производительность работы с DOM - здесь в статье перечислены [полезные источники](https://isoba
для себя хотел добавить, а у них домен поменялся)
надо ссылку на эту заменить: https://isobar-us.github.io/code-standards/#javascript_javascript_performance

2019-04-04 05:55 UTC, krashaen commented on JS/jQuery.md
> +    > * Выше было требование, что все обработчики должны быть отименованы. Тут это принимает еще более строгий характер — имена обработчиков для разных инстансов одного и того же класса должны быть у
@Znack тут не понял, куда именно вставить?

2019-04-04 05:57 UTC, Znack commented on JS/jQuery.md
> +    > * Выше было требование, что все обработчики должны быть отименованы. Тут это принимает еще более строгий характер — имена обработчиков для разных инстансов одного и того же класса должны быть у
> отключал события только для текущего инстанса блока, а не для всех инстансов (например, сразу для всех слайдеров на странице)

лучше поменять на 

> отключал события только для текущего инстанса блока, не для всех инстансов, а то неожиданно для разработчика сразу будут отключены обработчики события для всех слайдеров на странице

2019-04-04 05:57 UTC, Znack commented on JS/jQuery.md
> +    > * Выше было требование, что все обработчики должны быть отименованы. Тут это принимает еще более строгий характер — имена обработчиков для разных инстансов одного и того же класса должны быть у
Вот так пример переделал :)

2019-04-04 06:10 UTC, krashaen commented on JS/react.md
> +    > * Асинхронные `action creator` делать только с тремя `dispatch` и только для того, чтобы показать состояния одного процесса. То есть диспатчить сначала старт запроса, потом его завершение успеш
@Znack, @chmnkh хелпа нужна)

2019-04-04 06:10 UTC, MorganaLF commented on JS/jQuery.md
> +    > * Выше было требование, что все обработчики должны быть отименованы. Тут это принимает еще более строгий характер — имена обработчиков для разных инстансов одного и того же класса должны быть у
Здесь еще хотелось бы пример, как должно выглядеть уникальное имя обработчика события, поскольку scroll.myComponent из примера выше уже не подходит.

2019-04-04 06:40 UTC, NikitaRzm commented on JS/react.md
> +    >        <div>Order status: {this.renderStatusView(this.props.status)}</div>
Я бы для любого куска  jsx, который надо выносить заставлял уносить в компоненты, дело даже не столько в идиоматике - сколько в порядке: структурный элемент - компонент. Просто гибкость позволяет запихивать jsx в самые неожиданные углы, это бардак.  И потом - с непрваильно вынесенным jsx не удается работать как с полноценным react-unit, проблемы с рефами и отслеживаемостью в ДОМ, и т.д. Если выносим jsx - выносим в компонент.

2019-04-04 07:18 UTC, chmnkh commented on JS/react.md
> +    > * Асинхронные `action creator` делать только с тремя `dispatch` и только для того, чтобы показать состояния одного процесса. То есть диспатчить сначала старт запроса, потом его завершение успеш
По мне так тут вообще коряво написано, не понятен нифига смысл правила

2019-04-04 07:47 UTC, Znack commented on JS/react.md
> +    > * Асинхронные `action creator` делать только с тремя `dispatch` и только для того, чтобы показать состояния одного процесса. То есть диспатчить сначала старт запроса, потом его завершение успеш
Тебе вообще ничего не понятно, или понятно, но смутно, или норм понятно, если вчитать, но форма кривая? Лучше сразу конкретные вопросы кидай, а ещё лучше предлагай формулировки почище :)

2019-04-04 08:53 UTC, Zarwlar commented on JS/react.md
> +    > * Асинхронные `action creator` делать только с тремя `dispatch` и только для того, чтобы показать состояния одного процесса. То есть диспатчить сначала старт запроса, потом его завершение успеш
Лично я не понимаю смысл последнего предложения вообще. Возможно, стоит вместо него просто вставить ссылку [из доки редакса](https://redux.js.org/advanced/async-actions#actions). Или написать что-нибудь в духе:

> Это необходимо делать для того, чтобы различать момент начала вызова и его завершения. Причём завершение вызова может быть удачным или неудачным. Из этого и вытекает наличие трёх actions для каждого из состояния запроса

2019-04-04 08:54 UTC, NikitaRzm commented on JS/react.md
> +    > * Асинхронные `action creator` делать только с тремя `dispatch` и только для того, чтобы показать состояния одного процесса. То есть диспатчить сначала старт запроса, потом его завершение успеш
Это правило писалось относительно redux-thunk, сейчас оно некорректно, Бизнес логика там пишщется. Тут надо правило смещать скорее в ту сторону, что нужно сводить все диспатчи к одному месту и как можно меньшему количеству во избежание частых пересчетов состояния, или пересчитывать их за раз все :)

2019-04-04 10:05 UTC, krashaen commented on JS/react.md
> +    >        <div>Order status: {this.renderStatusView(this.props.status)}</div>
>Избегайте создания методов-рендеров в компонентах-классах (речь не о методе render, а о методах, которые вы можете написать помимо него, и которые тоже возвращают JSX).
Так как эти методы возвращают куски JSX, которые не являются полноценными react-unit объектами, у вас могут возникнуть проблемы с сопровождением этих компонент в дальнейшем.
>Если вы хотите вынести JSX — выносите его в stateless компоненту.

Может так напишем?) @Znack @NikitaRzm @Zarwlar

2019-04-04 15:11 UTC, Znack commented on JS/react.md
> +    >        <div>Order status: {this.renderStatusView(this.props.status)}</div>
Можно прямо как у Никиты мотивацию сформулировать :)

> И потом - с непрваильно вынесенным jsx не удается работать как с полноценным react-unit, проблемы с рефами и отслеживаемостью в ДОМ

2019-04-04 20:37 UTC, MorganaLF commented on JS/naming.md
> +    >    const [, city, zipCode] = address.match(cityZipCodeRegex) || [];
`const [, city, zipCode]`

В этом примере висячие запятые ставятся в начале, но нигде не конкретизируется, что это стандарт. В то время как в Airbnb напротив рекомендуется висячие запятые добавлять в конце. Может быть, стоит где-то уточнить в стандартах этот момент?

2019-04-04 20:47 UTC, sk1e commented on JS/naming.md
> +    >    const [, city, zipCode] = address.match(cityZipCodeRegex) || [];
Тут не висячие. Это синтаксис для пропуска ненужного первого элемента при деструктуризации

2019-04-04 20:49 UTC, MorganaLF commented on JS/naming.md
> +    >    const [, city, zipCode] = address.match(cityZipCodeRegex) || [];
Тогда понятно, вопрос снимается)

2019-04-05 02:49 UTC, krashaen commented on JS/naming.md
> +    >    const [, city, zipCode] = address.match(cityZipCodeRegex) || [];
> Тогда понятно, вопрос снимается)
Добавил нижнее подчеркивание для наглядности)

2019-04-05 03:47 UTC, in19farkt commented on JS/naming.md
> +    >    const [, city, zipCode] = address.match(cityZipCodeRegex) || [];
нижнее подчеркивание не нужно добавлять. Что мы будем делать если нужно будет много элементов пропустить, ведь нижнее подчеркивание - это имя константы, которое должно быть уникальным в пределах одной области видимости. И у меня на это тслинт орёт, что по моему логично :)

2019-04-05 03:51 UTC, krashaen commented on JS/naming.md
> +    >    const [, city, zipCode] = address.match(cityZipCodeRegex) || [];
> нижнее подчеркивание не нужно добавлять. Что мы будем делать если нужно будет много элементов пропустить, ведь нижнее подчеркивание - это имя константы, которое должно быть уникальным в пределах одной области видимости. И у меня на это тслинт орёт, что по моему логично :)

Просто, Сергей до этого тоже не обратил внимание что запятая отделяет первый итем в массиве)  [вот тут](https://github.com/fullstack-development/front-end-best-practices/pull/9#discussion_r271773607) поэтому я хочу явно показать

2019-04-05 03:55 UTC, in19farkt commented on JS/naming.md
> +    >    const [, city, zipCode] = address.match(cityZipCodeRegex) || [];
смотри, такой код (естественно там могут быть разные регулярки и разные пропускаемые элементы, это просто пример):
```
const [, city1, zipCode1] = address.match(cityZipCodeRegex1) || [];
const [,, zipCode2] = address.match(cityZipCodeRegex2) || [];
const [, city3, zipCode3] = address.match(cityZipCodeRegex3) || [];
const [,, zipCode4] = address.match(cityZipCodeRegex4) || [];
```
что будешь делать в таком случае?

2019-04-05 03:56 UTC, in19farkt commented on JS/naming.md
> +    >    const [, city, zipCode] = address.match(cityZipCodeRegex) || [];
если бы мы могли все пропуски заполнить с помощью `_`, но нет, нам придется для каждого пропускаемого элемента выдумывать уникальное имя и лишь одно из них может быть `_`

2019-04-05 04:12 UTC, krashaen commented on JS/naming.md
> +    >    const [, city, zipCode] = address.match(cityZipCodeRegex) || [];
я же не говорю про все, а именно по этот пример, он выдуманный и существует только в лабораторных условиях, поэтому и `_` стоит

2019-04-05 06:26 UTC, sk1e commented on JS/naming.md
> +    >    const [, city, zipCode] = address.match(cityZipCodeRegex) || [];
есть альтернатива которая может удовлетвориться вас обоих:

`const [{}, city, zipCode] = address.match(cityZipCodeRegex) || [];`

2019-04-05 06:35 UTC, sk1e commented on JS/naming.md
> +    >    const [, city, zipCode] = address.match(cityZipCodeRegex) || [];
> есть альтернатива, которая может удовлетворить вас обоих:
> 
> `const [{}, city, zipCode] = address.match(cityZipCodeRegex) || [];`

но для пустого массива это не работает и надо часть с `|| []` заменить полноценной проверкой, которая в любом случае предпочтительна в таких ситуациях

2019-04-05 08:29 UTC, in19farkt commented on JS/naming.md
> +    >    const [, city, zipCode] = address.match(cityZipCodeRegex) || [];
> он выдуманный и существует только в лабораторных условиях

Меня последнее время удивляет такой подход, от каждого второго слышу подобное. Мне кажется для того мы и пишем стандарты, чтобы применять их везде, не задумываясь о крайних "лабораторных" условиях, чтобы в момент появления в коде крайнего случая мне не пришлось переписывать код написанный ранее.

Возможно я придираюсь. @NikitaRzm @Znack рассудите плиз, может я реально загоняюсь сильно))

2019-04-05 08:33 UTC, Znack commented on JS/naming.md
> +    >    const [, city, zipCode] = address.match(cityZipCodeRegex) || [];
Не, подчеркивание не пойдёт, к сожалению, я за исходный вариант вообще :) Хотя там запятая не такая очевидная, но всё равно достаточно хорошо видно, что паттерн-матчинг на второй и третий элемент массива

2019-04-09 06:38 UTC, NikitaRzm approved these changes

2019-04-09 07:10 UTC, chmnkh approved these changes

2019-04-09 07:15 UTC, Znack approved these changes

2019-04-09 07:15 UTC, merged